### PR TITLE
Scale to 0 if <0

### PR DESCRIPTION
**Pull request by TimoRoth**
Prevents possible ValueError exceptions

### CODE REVIEW

**Comment by WoLpH** [comment]
Ah, yes. Great fix. Should have done that in the first place. Thanks!

**Comment by TimoRoth** [comment]
This change seems to have vanished from develop and master. Was this intended and there was an issues with this?

**Comment by WoLpH** [comment]
Odd, it appears git has somehow reverted it... I'll re-add it :)

**Comment by TimoRoth** [comment]
While 3.9.3 contains this fix now, it's gone again in master and develop.
Looks like some accidental force push got rid of the commit or something like that?

**Comment by WoLpH** [comment]
I haven't done a force push so I'm guessing something went wrong when merging (I generally do rebase merges) but I'm not entirely sure what... I've merged everything back so it's now included again including a few extra tests to make sure it won't break again :)

Thanks for all the help @TimoRoth

**Pull request merged**
