### PR TITLE
Add lazy update algorithm to prevent high CPU usage with large max_value

### PR DESCRIPTION
**Pull request by max-arnold**
Possible fix for #41

### CODE REVIEW

**Comment by WoLpH** [comment]
I believe this would break timed bar that don't get too many updates. For example, when processing large files it would still be useful to update every second so the progress bar shows a correct ETA but the actual value wouldn't change.

**Comment by max-arnold** [comment]
Does this look better?

```
    def _needs_update(self):
        'Returns whether the ProgressBar should redraw the line.'

        if self.poll_interval:
            delta = datetime.now() - self.last_update_time
            poll_status = delta > self.poll_interval

        # Do not update if value increment is not large enough to
        # add more bars to progressbar (according to current
        # terminal width)
        try:
            divisor = self.max_value / self.term_width  # float division
            if self.value // divisor == self.previous_value // divisor:
                if self.poll_interval:
                    return poll_status
                return False
        except:
            # ignore any division errors
            pass

        if self.value > self.next_update or self.end_time:
            return True
        elif self.poll_interval:
            return poll_status
```

**Comment by WoLpH** [comment]
Yes, that should work better :)

**Comment by WoLpH** [comment]
Thanks for all the help @max-arnold, I'll push out a new release soon :)

**Pull request merged**
