### PR TITLE
Fix unwrapping stdout/stderr

### PR DESCRIPTION
**Pull request by matthewwardrop**
Hi @WoLpH,

Looks like you've got a couple of off-by-one errors here, which leads to the stdout/stderr not being restored appropriately. Causing some bugs downstream :).

### CODE REVIEW

**Comment by WoLpH** [comment]
You're right, that doesn't work correctly. Although the fix is actually still a bit "wrong" as it keeps the counter at 1 once it's been incremented. Shouldn't really be a problem, but it's not as neat :P

I guess when resetting the stream it should just set the counter to 0 in all cases.

**Comment by matthewwardrop** [comment]
@WoLpH That was my fault... fixed. [It didn't always reset, since it is loaded at import time.]

**Comment by matthewwardrop** [comment]
Not sure what's triggering coverage that's different than master. Perhaps builds are broken there too?

When are you likely to be able to ship a new release with this patch?

**Comment by WoLpH** [comment]
My weekend is a bit busy but I might have time on sunday, monday at the latest :)

As for the tests, I'm guessing the tests are simply broken. They worked for the old (wrong) code so with the new code they need to be changed as well: https://github.com/WoLpH/python-progressbar/blob/6ca8abf16f8b7f2ca9d958ea19a7fe8887d9d403/tests/test_stream.py
I can take a look when I merge if you'd prefer, shouldn't be too hard to fix them

**Comment by matthewwardrop** [comment]
@WoLpH It's actually not the tests that are failing... but `coverage`. But since the patch only changes code within the methods, I'm not sure what's going on there.

Monday sounds great. Thanks for being so responsive!

**Comment by matthewwardrop** [comment]
I just realised as much (hitherto not used coverage). Will fix that too.

**Comment by WoLpH** [comment]
Testing locally is much easier than using travis :)

```
pip install -r tests/requirements.txt
py.test
```

After that you should have a `htmlcov` directory

**Comment by matthewwardrop** [comment]
Yep... figured it out :). Just adding a test now.

**Comment by matthewwardrop** [comment]
I added a fairly esoteric test to `test_stream.py`, which tests that progress bars work on non-standard file-type outputs (i.e. StringIO vs sys.stdout/sys.stderr), which rounds coverage back out to 100%. Feel free to modify the test if needed.

**Comment by WoLpH** [comment]
@matthewwardrop the new release is online and it seems to do the trick :)

Thanks for the help!

**Comment by matthewwardrop** [comment]
Thanks @WoLpH !

**Pull request merged**
