### PR TITLE
FormatCustomText

### PR DESCRIPTION
**Pull request by fvisin**
This PR adds a widget to print custom text.

### CODE REVIEW

**Comment by fvisin** [comment]
There is probably a smarter way to do it, this was a quick hack I wrote to solve the problem in my case.
I don't have much time to work on it, but if minor modifications are required I am glad to help, just let me know.

**Comment by WoLpH** [comment]
That looks like it would work fine but I'm not entirely sure I understand the point of this widget. Isn't it effectively just a static string this way?

Or would you use it by updating the mapping for every update as well?

**Comment by fvisin** [comment]
Sorry, I should have provided a code snippet. 
The way I use it is I keep a reference to the widget object and then call its `update_mapping` method before calling the `update` method of the progressbar:

```python
# Initialization
metrics_wid = VariableText(
        'Cost %(cost)f, DD %(DD)f, UD %(UD)f %(shape)s',
        {'cost': None,
         'DD': None,
         'UD': None,
         'shape': None})
pbar = ProgressBar(widgets= [ ' ', metrics_wid], maxval=nsamples).start()

# update loop
for i in range(nsamples):
    metrics_wid.update_mapping(
                    {'cost': float(cost),
                     'DD': dd,
                     'UD': ud,
                     'shape': input_shape})
    pbar.update(i)
```

**Comment by WoLpH** [comment]
I suppose that works but it's still a bit inconvenient since you only have those variables available. I think the proper solution would be to integrate it with the regular update method but I haven't had time yet. I do plan on working on a solution like that but I'm just really stretched in terms of time unfortunately.

**Comment by fvisin** [comment]
I agree. As I said this was a quick and dirty hack to get the result, but it's far from being optimal.

I suppose that modifying `update` to either accept a single value (current behavior) or a dictionary would be a good way to do this. With a small modification the widget could then directly fetch those values, without the need for the user to keep a reference to the widget and call two different update functions.

**Comment by WoLpH** [comment]
I think it's a good start so I've merged it with some minor changes. Can you check if this works for you?

I'm planning to push out a new release in the next few days

**Comment by fvisin** [comment]
I don't have time to look into it too much at the moment. I tried quickly and it's failing with this message:

> File "/u/visin/exp/python-progressbar/progressbar/bar.py", line 522, in start
>     self.update(self.min_value, force=True)
>   File "/u/visin/exp/python-progressbar/progressbar/bar.py", line 479, in update
>     StdRedirectMixin.update(self, value=value)
>   File "/u/visin/exp/python-progressbar/progressbar/bar.py", line 110, in update
>     DefaultFdMixin.update(self, value=value)
>   File "/u/visin/exp/python-progressbar/progressbar/bar.py", line 42, in update
>     self.fd.write('\r' + self._format_line())
>   File "/u/visin/exp/python-progressbar/progressbar/bar.py", line 416, in _format_line
>     widgets = ''.join(self._format_widgets())
>   File "/u/visin/exp/python-progressbar/progressbar/bar.py", line 396, in _format_widgets
>     widget_output = widget(self, data)
>   File "/u/visin/exp/python-progressbar/progressbar/widgets.py", line 589, in __call__
>     self.format)
>   File "/u/visin/exp/python-progressbar/progressbar/widgets.py", line 65, in __call__
>     return (format or self.format) % data
> TypeError: float argument required, not NoneType

The problem seems to be due to the fact that data is initialized as a dict full of `None`. Apart from the initialization, assuming that everything will be a float seems too restrictive to me.

If I initialize everything with 0.0, it fails at the first update:
> epochs_wid.update_mapping({'epoch': eidx, 'up': uidx})
TypeError: update_mapping() takes exactly 1 argument (2 given)

**Comment by WoLpH** [comment]
Thanks for the quick check, I'll take a look at it :)

I agree with you on the `float` part, I've just merged it as-is for the time being but it might need a bit of refining before it goes into production

**Pull request merged**
