### PR TITLE
Fix #146

### LINKED ISSUE #146: Flickering tests on Windows
#### Description

The
* test_failure.py and
* test_time.py 

are failing from time to time.
The reason might be the lower resolution of time ticks on windows.

It could be easily fixed by adding a time sleep(0.1). But that's not the right solution IMHO.
A possible solution could be to use  timeit.default_timer() in bar.py, which has a finer resolution on windows.

#### Versions

* Python 2.7.14 / Python 3.6.3
* Anconda 
* Windows 10
* Progressbar: 3.34.4

### PR DESCRIPTION
**Pull request by stuertz**
Skipped Tests on windows, where timer resolution is not that fine granular as expected by the test.

### CODE REVIEW

**Comment by WoLpH** [comment]
I've been trying to get the windows tests working again (i.e. skip those specific tests) without removing the coverage requirements for all platforms... so far I can't find a good way.

Do you have any suggestions?

**Comment by stuertz** [comment]
Maybe monkey patch a pseudo timer while running the windows tests. - OTH IMHO monkey patching the code to get 100% coverage isn't the right way.

Another way could be to leave out the timer check on windows. just run through the code, to have coverage, but accept that the timer resolution on win is different.

**Comment by WoLpH** [comment]
I think your first suggestion (in the ticket) might be better for now, it might give some problems in the future but a FAQ entry might work too ;)

Can you test if `timeit.default_timer` mitigates all problems for you?

**Comment by stuertz** [comment]
After rereading your last comment, it looks like I misunderstood you. I will try to give timeit.default_timer() a chance.

**Comment by WoLpH** [comment]
thank you for the help. If it works I'll create a new release today

**Comment by stuertz** [comment]
Maybe you can explain to me, why there is a last_update_time and a _last_update_time in bar.ProgressBar(). It looks to me as if it should be the same, but got rotten (or is there a secret plan behind that)?

Another thing is, that _last_update_time is exposed via API, it looks to be required, that the value represents some real world timestamp, and not something else (e.g. the result of timeit.default_timer(), or just a simple long counter. 
So my plan would be to add an internal variable, the represents the version of the object, but is something different than the last_update_time.

**Comment by WoLpH** [comment]
The last update time is actually a property that gets saved to the one with the underscore internally. So that should work for your case :)

**Comment by stuertz** [comment]
But it would break, if someone relies on reading the value of last_update_date, which is also part of data(). So I tried to separate those two concerns.
Sadly default_timer() returns time since first call, not sine first january of 1970 :-(

**Comment by WoLpH** [comment]
Indeed, I realized that after suggesting it... that's not a good idea. 

The fix is definitely a bit more work than anticipated

**Comment by WoLpH** [comment]
I've merged your changes and created the new release. Thanks for all the help @stuertz :)

**Pull request merged**
