### PR TITLE
Show initial progressbar when starting

### LINKED ISSUE #63: Progress bar is not plotting when progress is equal to 0
Considering the following code,
```python
from progressbar import ProgressBar
import time

with ProgressBar(max_value=10) as pbar:
    for i in range(10):
        # long, loooong wait
        sleep(10000000)
        pbar.update(i)
```

Running that, it will take a long time for the process bar get printed. It does not print 0% progress, what is useful for iterations that requires long time to run.

I found the bug both on `progressbar2==3.6.2` and `git+https://github.com/WoLpH/python-progressbar.git@develop`

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #63.

### CODE REVIEW

**Comment by cbrnr** [comment]
Many tests fail because logarithmic scaling doesn't work for the value 0 - any ideas how to address this?

**Comment by WoLpH** [comment]
Since it doesn't work for 0 I think the best solution would be to exclude that value with an if statement.
We can simply assume that the log of 0 = 0 in this case.

**Comment by cbrnr** [comment]
Any idea what's going on with the coverage? I get 100% coverage if I run `py.test` locally on my machine...

**Comment by WoLpH** [comment]
Everything looks good :) The appveyer build can be ignored for the time being, I'll look at that when I push a new release soon.

Thank you very much for the help!

**Pull request merged**
